<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[Reading data from peroperty file]]>
    </line>
    <line>
      <![CDATA[data is https://neostox.com/]]>
    </line>
    <line>
      <![CDATA[waiting for 1000ms]]>
    </line>
    <line>
      <![CDATA[Launching Browser]]>
    </line>
    <line>
      <![CDATA[clicking on signin button]]>
    </line>
    <line>
      <![CDATA[waiting for 1000ms]]>
    </line>
    <line>
      <![CDATA[Reading data from peroperty file]]>
    </line>
    <line>
      <![CDATA[data is 886207114]]>
    </line>
    <line>
      <![CDATA[Entering mobile number]]>
    </line>
    <line>
      <![CDATA[Clicking on sign in button]]>
    </line>
    <line>
      <![CDATA[Actual Eror MSg is ]]>
    </line>
  </reporter-output>
  <suite started-at="2023-01-14T18:28:57 IST" name="Default suite" finished-at="2023-01-14T18:29:42 IST" duration-ms="45040">
    <groups>
    </groups>
    <test started-at="2023-01-14T18:28:57 IST" name="Default test" finished-at="2023-01-14T18:29:42 IST" duration-ms="45040">
      <class name="validateErrorMsg.ValidateErrorMSgOfMObNumField$ValidateErrorMessageOfMobNumField">
        <test-method is-config="true" signature="browserLaunch()[pri:0, instance:validateErrorMsg.ValidateErrorMSgOfMObNumField$ValidateErrorMessageOfMobNumField@6404f418]" started-at="2023-01-14T18:28:57 IST" name="browserLaunch" finished-at="2023-01-14T18:29:32 IST" duration-ms="35211" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Reading data from peroperty file]]>
            </line>
            <line>
              <![CDATA[data is https://neostox.com/]]>
            </line>
            <line>
              <![CDATA[waiting for 1000ms]]>
            </line>
            <line>
              <![CDATA[Launching Browser]]>
            </line>
          </reporter-output>
        </test-method> <!-- browserLaunch -->
        <test-method signature="loginToNeostox()[pri:0, instance:validateErrorMsg.ValidateErrorMSgOfMObNumField$ValidateErrorMessageOfMobNumField@6404f418]" started-at="2023-01-14T18:29:32 IST" name="loginToNeostox" finished-at="2023-01-14T18:29:38 IST" duration-ms="5809" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [TC is Failed As Act ANd Exp Didn't Matched] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [TC is Failed As Act ANd Exp Didn't Matched] but found []
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at neoStoxPOMClassForBaseNutility.NeoStoxSignInPage.validateErrorMsg(NeoStoxSignInPage.java:42)
at validateErrorMsg.ValidateErrorMSgOfMObNumField$ValidateErrorMessageOfMobNumField.loginToNeostox(ValidateErrorMSgOfMObNumField.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[clicking on signin button]]>
            </line>
            <line>
              <![CDATA[waiting for 1000ms]]>
            </line>
            <line>
              <![CDATA[Reading data from peroperty file]]>
            </line>
            <line>
              <![CDATA[data is 886207114]]>
            </line>
            <line>
              <![CDATA[Entering mobile number]]>
            </line>
            <line>
              <![CDATA[Clicking on sign in button]]>
            </line>
            <line>
              <![CDATA[Actual Eror MSg is ]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginToNeostox -->
        <test-method is-config="true" signature="closeBrowse()[pri:0, instance:validateErrorMsg.ValidateErrorMSgOfMObNumField$ValidateErrorMessageOfMobNumField@6404f418]" started-at="2023-01-14T18:29:38 IST" name="closeBrowse" finished-at="2023-01-14T18:29:42 IST" duration-ms="3894" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowse -->
      </class> <!-- validateErrorMsg.ValidateErrorMSgOfMObNumField$ValidateErrorMessageOfMobNumField -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
